services:
  signaling-server:
    container_name: signaling-server
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: always
